package netconf

import (
	"bytes"
	"io"
	"strings"
	"testing"
	"unicode"
)

func TestTrimReader_Read(t *testing.T) {

	ncReader := NewReplyReader(strings.NewReader(SRX240NewlineRPC))
	var buf bytes.Buffer
	written, err := io.Copy(&buf, ncReader)
	if err != nil {
		t.Errorf("io.Copy error after %d bytes written: %v", written, err)
	}

	wantBytes := bytes.TrimSuffix(bytes.TrimRightFunc([]byte(SRX240NewlineRPC), unicode.IsSpace), messageSeparatorBytes)

	if !bytes.Equal(wantBytes, buf.Bytes()) {
		t.Errorf("unexpected reader output:\nwant:\t%q\ngot:\t%q",
			string(wantBytes), buf.String())
	}

	if br, err := ncReader.Read(make([]byte, 8)); err != io.EOF {
		t.Errorf("unexpected error returned from reader:\nwant:\t%v\ngot:\t%v", io.EOF, err)
	} else if br != 0 {
		t.Errorf("unexpected byte read count returned from reader:\nwant:\t%d\ngot:\t%d", 0, br)
	}
}

const SRX240NewlineRPC = `<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
<interface-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-interface" junos:style="normal">
<physical-interface>
<name>
ge-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
136
</local-index>
<snmp-index>
508
</snmp-index>
<description>
gateway
</description>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<if-config-flags>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:41
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:41
</hardware-physical-address>
<interface-flapped junos:seconds="466995">
2017-07-30 17:01:59 EDT (5d 09:43 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
11024456
</input-bps>
<input-pps>
922
</input-pps>
<output-bps>
163176
</output-bps>
<output-pps>
375
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/0.0
</name>
<local-index>
73
</local-index>
<snmp-index>
510
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
ENET2
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
706767293
</input-packets>
<output-packets>
294204881
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
untrust
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
<inbound-dhcp/>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
1500
</mtu>
<address-family-flags>
<ifff-sendbcast-pkt-to-re/>
</address-family-flags>
<interface-address>
<ifa-flags>
<ifaf-current-preferred/>
<ifaf-current-primary/>
</ifa-flags>
<ifa-destination>
71.92.32/22
</ifa-destination>
<ifa-local>
71.92.32.147
</ifa-local>
<ifa-broadcast>
71.92.35.255
</ifa-broadcast>
</interface-address>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
gr-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
153
</local-index>
<snmp-index>
529
</snmp-index>
<if-type>
GRE
</if-type>
<link-level-type>
GRE
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
800mbps
</speed>

<if-media-flags>
<ifmf-keepalives/>
<ifmf-dte/>
<ifmf-scheduler/>
</if-media-flags>
<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-point-to-point/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
ip-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
154
</local-index>
<snmp-index>
530
</snmp-index>
<if-type>
IPIP
</if-type>
<link-level-type>
IP-over-IP
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
800mbps
</speed>

<if-media-flags>
<ifmf-keepalives/>
<ifmf-dte/>
<ifmf-scheduler/>
</if-media-flags>
<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
lsq-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
155
</local-index>
<snmp-index>
531
</snmp-index>
<link-level-type>
LinkService
</link-level-type>
<mtu>
1504
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<if-config-flags>
<iff-point-to-point/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<interface-flapped junos:seconds="2993772">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
lt-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
157
</local-index>
<snmp-index>
534
</snmp-index>
<if-type>
Logical-tunnel
</if-type>
<link-level-type>
Logical-tunnel
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
800mbps
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-point-to-point/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-information>
13
</physical-information>
<current-physical-address junos:format="MAC 0c:86:10:1c:22:41">
0c:86:10:1c:22:41
</current-physical-address>
<hardware-physical-address junos:format="MAC 0c:86:10:1c:22:41">
0c:86:10:1c:22:41
</hardware-physical-address>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
mt-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
156
</local-index>
<snmp-index>
533
</snmp-index>
<if-type>
Multicast-GRE
</if-type>
<link-level-type>
GRE
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
800mbps
</speed>

<if-media-flags>
<ifmf-keepalives/>
<ifmf-dte/>
</if-media-flags>
<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
sp-0/0/0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
152
</local-index>
<snmp-index>
528
</snmp-index>
<if-type>
Adaptive-Services
</if-type>
<link-level-type>
Adaptive-Services
</link-level-type>
<mtu>
9192
</mtu>
<speed>
800mbps
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-point-to-point/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<link-type>
Full-Duplex
</link-type>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<interface-flapped junos:seconds="2993772">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<logical-interface>
<name>
sp-0/0/0.0
</name>
<local-index>
89
</local-index>
<snmp-index>
546
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-point-to-point/>
<iff-snmp-traps/>
</if-config-flags>
<encapsulation>
Adaptive-Services
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
9192
</mtu>
<address-family-flags>
<ifff-recv-ttl-exceeded/>
<ifff-recv-options/>
</address-family-flags>
</address-family>
<address-family>
<address-family-name>
inet6
</address-family-name>
<mtu>
9192
</mtu>
<max-local-cache>
0
</max-local-cache>
<new-hold-limit>
0
</new-hold-limit>
<intf-curr-cnt>
0
</intf-curr-cnt>
<intf-unresolved-cnt>
0
</intf-unresolved-cnt>
<intf-dropcnt>
0
</intf-dropcnt>
<address-family-flags>
<ifff-primary/>
<ifff-is-primary/>
<ifff-recv-ttl-exceeded/>
<ifff-recv-options/>
</address-family-flags>
</address-family>
</logical-interface>
<logical-interface>
<name>
sp-0/0/0.16383
</name>
<local-index>
90
</local-index>
<snmp-index>
547
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-point-to-point/>
<iff-snmp-traps/>
</if-config-flags>
<encapsulation>
Adaptive-Services
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
9192
</mtu>
<address-family-flags>
<ifff-is-primary/>
<ifff-recv-ttl-exceeded/>
<ifff-recv-options/>
</address-family-flags>
<interface-address>
<ifa-flags>
<ifaf-current-preferred/>
<ifaf-current-primary/>
</ifa-flags>
<ifa-destination>
10.0.0.16
</ifa-destination>
<ifa-local>
10.0.0.1
</ifa-local>
</interface-address>
<interface-address heading="Addresses">
<ifa-local>
10.0.0.6
</ifa-local>
</interface-address>
<interface-address>
<ifa-flags>
<ifaf-current-preferred/>
</ifa-flags>
<ifa-destination>
128.0.1.16
</ifa-destination>
<ifa-local>
128.0.0.1
</ifa-local>
</interface-address>
<interface-address heading="Addresses">
<ifa-local>
128.0.0.6
</ifa-local>
</interface-address>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/1
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
137
</local-index>
<snmp-index>
509
</snmp-index>
<description>
ex2200c1
</description>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<if-config-flags>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:42
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:42
</hardware-physical-address>
<interface-flapped junos:seconds="1998745">
2017-07-12 23:32:50 EDT (3w2d 03:12 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
253712
</input-bps>
<input-pps>
441
</input-pps>
<output-bps>
12336728
</output-bps>
<output-pps>
1018
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/1.0
</name>
<local-index>
74
</local-index>
<snmp-index>
514
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
75710
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<ifff-is-primary/>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/2
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
138
</local-index>
<snmp-index>
511
</snmp-index>
<description>
ex2200c2
</description>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:43
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:43
</hardware-physical-address>
<interface-flapped junos:seconds="216928">
2017-08-02 14:29:47 EDT (2d 12:15 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/2.0
</name>
<local-index>
75
</local-index>
<snmp-index>
522
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
2049
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/3
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
139
</local-index>
<snmp-index>
512
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<if-config-flags>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:44
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:44
</hardware-physical-address>
<interface-flapped junos:seconds="1825551">
2017-07-14 23:39:24 EDT (3w0d 03:05 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/3.0
</name>
<local-index>
76
</local-index>
<snmp-index>
527
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
182
</input-packets>
<output-packets>
107887
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/4
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
140
</local-index>
<snmp-index>
513
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<if-config-flags>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:45
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:45
</hardware-physical-address>
<interface-flapped junos:seconds="2993768">
2017-07-01 11:09:07 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
1264
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/4.0
</name>
<local-index>
77
</local-index>
<snmp-index>
532
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
107870
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/5
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
141
</local-index>
<snmp-index>
515
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:46
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:46
</hardware-physical-address>
<interface-flapped junos:seconds="2993773">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/5.0
</name>
<local-index>
78
</local-index>
<snmp-index>
535
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/6
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
142
</local-index>
<snmp-index>
516
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:47
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:47
</hardware-physical-address>
<interface-flapped junos:seconds="1375087">
2017-07-20 04:47:09 EDT (2w1d 21:58 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/6.0
</name>
<local-index>
79
</local-index>
<snmp-index>
536
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
8994
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/7
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
143
</local-index>
<snmp-index>
517
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<if-config-flags>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:48
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:48
</hardware-physical-address>
<interface-flapped junos:seconds="2993769">
2017-07-01 11:09:07 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
512
</input-bps>
<input-pps>
1
</input-pps>
<output-bps>
630112
</output-bps>
<output-pps>
450
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<alarm-not-present/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/7.0
</name>
<local-index>
80
</local-index>
<snmp-index>
537
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
2852581
</input-packets>
<output-packets>
1306616
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/8
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
144
</local-index>
<snmp-index>
518
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:49
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:49
</hardware-physical-address>
<interface-flapped junos:seconds="2993773">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/8.0
</name>
<local-index>
81
</local-index>
<snmp-index>
538
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/9
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
145
</local-index>
<snmp-index>
519
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:4a
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:4a
</hardware-physical-address>
<interface-flapped junos:seconds="2993773">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/9.0
</name>
<local-index>
82
</local-index>
<snmp-index>
539
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/10
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
146
</local-index>
<snmp-index>
520
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:4b
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:4b
</hardware-physical-address>
<interface-flapped junos:seconds="2993773">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/10.0
</name>
<local-index>
83
</local-index>
<snmp-index>
540
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/11
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
147
</local-index>
<snmp-index>
521
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:4c
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:4c
</hardware-physical-address>
<interface-flapped junos:seconds="2993773">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/11.0
</name>
<local-index>
84
</local-index>
<snmp-index>
541
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/12
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
148
</local-index>
<snmp-index>
523
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:4d
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:4d
</hardware-physical-address>
<interface-flapped junos:seconds="2993773">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/12.0
</name>
<local-index>
85
</local-index>
<snmp-index>
542
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/13
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
149
</local-index>
<snmp-index>
524
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:4e
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:4e
</hardware-physical-address>
<interface-flapped junos:seconds="2993774">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/13.0
</name>
<local-index>
86
</local-index>
<snmp-index>
543
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/14
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
150
</local-index>
<snmp-index>
525
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:4f
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:4f
</hardware-physical-address>
<interface-flapped junos:seconds="2993774">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/14.0
</name>
<local-index>
87
</local-index>
<snmp-index>
544
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
ge-0/0/15
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
151
</local-index>
<snmp-index>
526
</snmp-index>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>
<sonet-mode>
LAN-PHY
</sonet-mode>
<source-filtering>
disabled
</source-filtering>
<link-mode>
Full-duplex
</link-mode>
<speed>
1000mbps
</speed>
<bpdu-error>
none
</bpdu-error>
<l2pt-error>
none
</l2pt-error>
<loopback>
disabled
</loopback>
<if-flow-control>
disabled
</if-flow-control>
<if-auto-negotiation>
enabled
</if-auto-negotiation>
<if-remote-fault>
online
</if-remote-fault>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address>
0c:86:10:1c:22:50
</current-physical-address>
<hardware-physical-address>
0c:86:10:1c:22:50
</hardware-physical-address>
<interface-flapped junos:seconds="2993774">
2017-07-01 11:09:03 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
<active-alarms>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-alarms>
<active-defects>
<interface-alarms>
<ethernet-alarm-link-down/>
</interface-alarms>
</active-defects>
<interface-transmit-statistics>
Disabled
</interface-transmit-statistics>
<logical-interface>
<name>
ge-0/0/15.0
</name>
<local-index>
88
</local-index>
<snmp-index>
545
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
Ethernet-Bridge
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
eth-switch
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<internal-flags>
0x4040
</internal-flags>
</address-family-flags>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
fxp0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
1
</local-index>
<snmp-index>
1
</snmp-index>
<if-type>
Ethernet
</if-type>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-no-carrier/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-hardware-down/>
<iff-snmp-traps/>
</if-config-flags>
<if-media-flags>
<internal-flags>
0x0
</internal-flags>
</if-media-flags>
<current-physical-address junos:format="MAC 0c:86:10:1c:22:40">
0c:86:10:1c:22:40
</current-physical-address>
<hardware-physical-address junos:format="MAC 0c:86:10:1c:22:40">
0c:86:10:1c:22:40
</hardware-physical-address>
<interface-flapped junos:seconds="2993846">
2017-07-01 11:07:51 EDT (4w6d 15:37 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<logical-interface>
<name>
fxp0.0
</name>
<local-index>
3
</local-index>
<snmp-index>
13
</snmp-index>
<if-config-flags>
<iff-device-down/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
ENET2
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
1500
</mtu>
<address-family-flags>
<ifff-is-primary/>
<ifff-sendbcast-pkt-to-re/>
</address-family-flags>
<interface-address>
<ifa-flags>
<ifaf-down/>
<ifaf-current-default/>
<ifaf-current-preferred/>
<ifaf-current-primary/>
</ifa-flags>
<ifa-destination>
192.168.1/24
</ifa-destination>
<ifa-local>
192.168.1.1
</ifa-local>
<ifa-broadcast>
192.168.1.255
</ifa-broadcast>
</interface-address>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
fxp2
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
3
</local-index>
<snmp-index>
3
</snmp-index>
<if-type>
Ethernet
</if-type>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<current-physical-address junos:format="MAC 00:00:00:00:00:00">
00:00:00:00:00:00
</current-physical-address>
<hardware-physical-address junos:format="MAC 00:00:00:00:00:00">
00:00:00:00:00:00
</hardware-physical-address>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
2993847
</output-packets>
</traffic-statistics>
<logical-interface>
<name>
fxp2.0
</name>
<local-index>
4
</local-index>
<snmp-index>
15
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
ENET2
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
2993847
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<address-family>
<address-family-name>
tnp
</address-family-name>
<mtu>
1500
</mtu>
<address-family-flags>
<ifff-is-primary/>
</address-family-flags>
<interface-address heading="Addresses">
<ifa-local>
0x1
</ifa-local>
</interface-address>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
gre
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
10
</local-index>
<snmp-index>
8
</snmp-index>
<if-type>
GRE
</if-type>
<link-level-type>
GRE
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-media-flags>
<ifmf-keepalives/>
<ifmf-dte/>
</if-media-flags>
<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-point-to-point/>
<iff-snmp-traps/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
ipip
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
11
</local-index>
<snmp-index>
9
</snmp-index>
<if-type>
IPIP
</if-type>
<link-level-type>
IP-over-IP
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-media-flags>
<ifmf-keepalives/>
<ifmf-dte/>
</if-media-flags>
<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
irb
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
130
</local-index>
<snmp-index>
502
</snmp-index>
<if-type>
Ethernet
</if-type>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<link-type>
Full-Duplex
</link-type>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<current-physical-address junos:format="MAC 0c:86:10:1c:22:f0">
0c:86:10:1c:22:f0
</current-physical-address>
<hardware-physical-address junos:format="MAC 0c:86:10:1c:22:f0">
0c:86:10:1c:22:f0
</hardware-physical-address>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<logical-interface>
<name>
irb.0
</name>
<local-index>
72
</local-index>
<snmp-index>
550
</snmp-index>
<if-config-flags>
<iff-up/>
<iff-snmp-traps/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
ENET2
</encapsulation>
<logical-interface-bandwidth>
1000mbps
</logical-interface-bandwidth>
<irb-domain>
<irb-routing-instance>
default-switch
</irb-routing-instance>
<irb-bridge>
vlan-trust
</irb-bridge>
</irb-domain>
<traffic-statistics junos:style="brief">
<input-packets>
300713208
</input-packets>
<output-packets>
701280550
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
trust
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
<inbound-bootp/>
<inbound-dns/>
<inbound-dhcp/>
<inbound-finger/>
<inbound-ftp/>
<ident-reset/>
<inbound-http/>
<inbound-https/>
<inbound-ike/>
<inbound-netconf/>
<inbound-ping/>
<inbound-rlogin/>
<inbound-rpm/>
<inbound-reverse-telnet/>
<inbound-reverse-ssh/>
<inbound-rsh/>
<inbound-snmp/>
<inbound-snmp-trap/>
<inbound-ssh/>
<inbound-telnet/>
<inbound-traceroute/>
<inbound-xnm-clear-text/>
<inbound-xnm-ssl/>
<inbound-tftp/>
<inbound-lsping/>
<inbound-ntp/>
<inbound-sip/>
<inbound-r2cp/>
<inbound-webapi-clear-text/>
<inbound-webapi-ssl/>
<inbound-bfd/>
<inbound-bgp/>
<inbound-dvmrp/>
<inbound-igmp/>
<inbound-ldp/>
<inbound-msdp/>
<inbound-nhrp/>
<inbound-ospf/>
<inbound-pgm/>
<inbound-pim/>
<inbound-rip/>
<inbound-router-discovery/>
<inbound-rsvp/>
<inbound-sap/>
<inbound-vrrp/>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
1500
</mtu>
<address-family-flags>
<ifff-sendbcast-pkt-to-re/>
</address-family-flags>
<interface-address>
<ifa-flags>
<ifaf-current-preferred/>
<ifaf-current-primary/>
</ifa-flags>
<ifa-destination>
192.168.2/24
</ifa-destination>
<ifa-local>
192.168.2.1
</ifa-local>
<ifa-broadcast>
192.168.2.255
</ifa-broadcast>
</interface-address>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
jsrv
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
128
</local-index>
<snmp-index>
548
</snmp-index>
<if-type>
Ethernet
</if-type>
<link-level-type>
Ethernet
</link-level-type>
<mtu>
1514
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
</if-config-flags>
<link-type>
Full-Duplex
</link-type>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<current-physical-address junos:format="MAC 0c:86:10:1c:22:41">
0c:86:10:1c:22:41
</current-physical-address>
<hardware-physical-address junos:format="MAC 0c:86:10:1c:22:41">
0c:86:10:1c:22:41
</hardware-physical-address>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<logical-interface>
<name>
jsrv.1
</name>
<local-index>
66
</local-index>
<snmp-index>
549
</snmp-index>
<if-config-flags>
<iff-up/>
<internal-flags>
0x0
</internal-flags>
</if-config-flags>
<encapsulation>
unknown
</encapsulation>
<logical-interface-bandwidth>
1000mbps
</logical-interface-bandwidth>
<irb-domain>
<irb-routing-instance>
None
</irb-routing-instance>
<irb-bridge>
None
</irb-bridge>
</irb-domain>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
1514
</mtu>
<address-family-flags>
<ifff-is-primary/>
</address-family-flags>
<interface-address>
<ifa-flags>
<ifaf-primary/>
<ifaf-current-default/>
<ifaf-current-preferred/>
<ifaf-current-primary/>
</ifa-flags>
<ifa-destination>
128/2
</ifa-destination>
<ifa-local>
128.0.0.127
</ifa-local>
<ifa-broadcast>
191.255.255.255
</ifa-broadcast>
</interface-address>
</address-family>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
lo0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
6
</local-index>
<snmp-index>
6
</snmp-index>
<if-type>
Loopback
</if-type>
<mtu>
Unlimited
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-loopback/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
26360201
</input-packets>
<output-packets>
26360201
</output-packets>
</traffic-statistics>
<logical-interface>
<name>
lo0.16384
</name>
<local-index>
67
</local-index>
<snmp-index>
21
</snmp-index>
<if-config-flags>
<iff-down/>
<iff-snmp-traps/>
</if-config-flags>
<encapsulation>
Unspecified
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
Unlimited
</mtu>
<address-family-flags>
<ifff-none/>
</address-family-flags>
<interface-address heading="Addresses">
<ifa-local>
127.0.0.1
</ifa-local>
</interface-address>
</address-family>
</logical-interface>
<logical-interface>
<name>
lo0.16385
</name>
<local-index>
68
</local-index>
<snmp-index>
22
</snmp-index>
<if-config-flags>
<iff-down/>
<iff-snmp-traps/>
</if-config-flags>
<encapsulation>
Unspecified
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
26360191
</input-packets>
<output-packets>
26360191
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
<address-family>
<address-family-name>
inet
</address-family-name>
<mtu>
Unlimited
</mtu>
<address-family-flags>
<ifff-none/>
</address-family-flags>
<interface-address>
<ifa-flags>
<ifaf-current-default/>
<ifaf-current-primary/>
</ifa-flags>
<ifa-local>
10.0.0.1
</ifa-local>
</interface-address>
<interface-address heading="Addresses">
<ifa-local>
10.0.0.16
</ifa-local>
</interface-address>
<interface-address heading="Addresses">
<ifa-local>
128.0.0.1
</ifa-local>
</interface-address>
<interface-address heading="Addresses">
<ifa-local>
128.0.0.4
</ifa-local>
</interface-address>
<interface-address heading="Addresses">
<ifa-local>
128.0.1.16
</ifa-local>
</interface-address>
</address-family>
</logical-interface>
<logical-interface>
<name>
lo0.32768
</name>
<local-index>
64
</local-index>
<snmp-index>
251
</snmp-index>
<encapsulation>
Unspecified
</encapsulation>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
<filter-information>
</filter-information>
<logical-interface-zone-name>
Null
</logical-interface-zone-name>
<allowed-host-inbound-traffic>
</allowed-host-inbound-traffic>
</logical-interface>
</physical-interface>
<physical-interface>
<name>
lsi
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
4
</local-index>
<snmp-index>
4
</snmp-index>
<if-type>
Software-Pseudo
</if-type>
<link-level-type>
LSI
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
mtun
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
64
</local-index>
<snmp-index>
12
</snmp-index>
<if-type>
Multicast-GRE
</if-type>
<link-level-type>
GRE
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-media-flags>
<ifmf-keepalives/>
<ifmf-dte/>
</if-media-flags>
<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
pimd
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
26
</local-index>
<snmp-index>
11
</snmp-index>
<if-type>
PIMD
</if-type>
<link-level-type>
PIM-Decapsulator
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
pime
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
25
</local-index>
<snmp-index>
10
</snmp-index>
<if-type>
PIME
</if-type>
<link-level-type>
PIM-Encapsulator
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
pp0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
129
</local-index>
<snmp-index>
501
</snmp-index>
<if-type>
PPPoE
</if-type>
<link-level-type>
PPPoE
</link-level-type>
<mtu>
1532
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-point-to-point/>
<iff-snmp-traps/>
</if-config-flags>
<link-type>
Full-Duplex
</link-type>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
ppd0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
133
</local-index>
<snmp-index>
505
</snmp-index>
<if-type>
PIMD
</if-type>
<link-level-type>
PIM-Decapsulator
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
800mbps
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
<internal-flags>
0x0
</internal-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
ppe0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
134
</local-index>
<snmp-index>
506
</snmp-index>
<if-type>
PIME
</if-type>
<link-level-type>
PIM-Encapsulator
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
800mbps
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
<internal-flags>
0x0
</internal-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
st0
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
132
</local-index>
<snmp-index>
504
</snmp-index>
<if-type>
Secure-Tunnel
</if-type>
<link-level-type>
Secure-Tunnel
</link-level-type>
<mtu>
9192
</mtu>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-point-to-point/>
</if-config-flags>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
tap
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
12
</local-index>
<snmp-index>
7
</snmp-index>
<if-type>
Software-Pseudo
</if-type>
<link-level-type>
Interface-Specific
</link-level-type>
<mtu>
Unlimited
</mtu>
<speed>
Unlimited
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
vlan
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
down
</oper-status>
<local-index>
135
</local-index>
<snmp-index>
507
</snmp-index>
<if-type>
VLAN
</if-type>
<link-level-type>
VLAN
</link-level-type>
<mtu>
1518
</mtu>
<speed>
10000mbps
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
<ifdf-down/>
</if-device-flags>
<if-config-flags>
<iff-hardware-down/>
</if-config-flags>
<link-type>
Full-Duplex
</link-type>
<if-media-flags>
<internal-flags>
0x0
</internal-flags>
</if-media-flags>
<physical-interface-cos-information>
<physical-interface-cos-hw-max-queues>
8
</physical-interface-cos-hw-max-queues>
<physical-interface-cos-use-max-queues>
8
</physical-interface-cos-use-max-queues>
</physical-interface-cos-information>
<current-physical-address junos:format="MAC 0c:86:10:1c:22:51">
0c:86:10:1c:22:51
</current-physical-address>
<hardware-physical-address junos:format="MAC 0c:86:10:1c:22:51">
0c:86:10:1c:22:51
</hardware-physical-address>
<interface-flapped junos:seconds="2993796">
2017-07-01 11:08:42 EDT (4w6d 15:36 ago)
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-bps>
0
</input-bps>
<input-pps>
0
</input-pps>
<output-bps>
0
</output-bps>
<output-pps>
0
</output-pps>
</traffic-statistics>
</physical-interface>
<physical-interface>
<name>
vtep
</name>
<admin-status junos:format="Enabled">
up
</admin-status>
<oper-status>
up
</oper-status>
<local-index>
131
</local-index>
<snmp-index>
503
</snmp-index>
<if-type>
Software-Pseudo
</if-type>
<link-level-type>
VxLAN-Tunnel-Endpoint
</link-level-type>
<mtu>
1600
</mtu>
<speed>
Unlimited
</speed>

<if-device-flags>
<ifdf-present/>
<ifdf-running/>
</if-device-flags>
<ifd-specific-config-flags>
</ifd-specific-config-flags>
<if-config-flags>
<iff-snmp-traps/>
</if-config-flags>
<link-type>
Full-Duplex
</link-type>
<if-media-flags>
<ifmf-none/>
</if-media-flags>
<interface-flapped junos:seconds="0">
Never
</interface-flapped>
<traffic-statistics junos:style="brief">
<input-packets>
0
</input-packets>
<output-packets>
0
</output-packets>
</traffic-statistics>
</physical-interface>
</interface-information>
</rpc-reply>
]]>]]>

`
